In [1]:
import numpy as np

In [2]:
temps_array = np.array([22.5, 25.0, 19.8, 30.2, 28.1])

1.

In [3]:
np.shape(temps_array)

(5,)

2.

In [4]:
np.mean(temps_array)

np.float64(25.119999999999997)

3.

In [7]:
np.sum(temps_array > 25)

np.int64(2)

4.

In [6]:
np.max(temps_array)

np.float64(30.2)

5.

In [8]:
np.sum(temps_array >= 20)

np.int64(4)

6.

In [9]:
np.std(temps_array)

np.float64(3.738127873682226)

7.

In [12]:
np.min(temps_array)

np.float64(19.8)

8.

In [11]:
np.sum(temps_array == 25.0)

np.int64(1)

9.

In [10]:
np.median(temps_array)

np.float64(25.0)

10.

In [16]:
np.sum(temps_array > 28)

np.int64(2)

11.

In [15]:
np.sum(temps_array)

np.float64(125.6)

12.

In [14]:
np.sum(temps_array < 22) 

np.int64(1)

13.

In [13]:
np.mean(temps_array + 2) 

np.float64(27.119999999999997)

14.

In [21]:
np.sum(temps_array > 24)  

np.int64(3)

15.

In [20]:
np.var(temps_array) 

np.float64(13.9736)

16.

In [19]:
np.where((temps_array >= 20) & (temps_array <= 25))

(array([0, 1]),)

17.

In [18]:
np.percentile(temps_array, 75) 

np.float64(28.1)

18.

In [17]:
np.sum(temps_array > 26)

np.int64(2)

19.

In [22]:
np.min(temps_array - 5)

np.float64(14.8)

20.

In [23]:
np.sum(temps_array == 30.2)

np.int64(1)

SCENARIO 2


In [24]:
sales_array = np.array([[100, 120, 90, 110], [80, 85, 95, 100], [150, 130, 140, 135]])

1.

In [25]:
np.shape(sales_array)

(3, 4)

2.

In [26]:
np.mean(sales_array[0])

np.float64(105.0)

3.

In [ ]:
np.sum(sales_array > 100)


np.int64(6)

4.

In [32]:
np.sum(sales_array[:, -2:])

np.int64(670)

5.

In [31]:
np.sum(sales_array[1] > 120)

np.int64(0)

6.

In [30]:
np.max(sales_array) 

np.int64(150)

7.

In [29]:
np.std(sales_array[:, 0]) 

np.float64(29.43920288775949)

8.

In [28]:
np.sum(sales_array == 100)  

np.int64(2)

9.

In [39]:
np.median(sales_array[1])

np.float64(90.0)

10.

In [38]:
np.sum(sales_array[1:3] > 100)

np.int64(4)

11.

In [37]:
np.sum(sales_array) 

np.int64(1335)

12.

In [36]:
np.sum(sales_array < 90) 

np.int64(2)

13.

In [35]:
np.mean(sales_array[:, -2:]) 

np.float64(111.66666666666667)

14.

In [34]:
np.sum(sales_array[0] > 110) 

np.int64(1)

SCENARIO 3

1.

In [40]:
np.unique(sales_array)

array([ 80,  85,  90,  95, 100, 110, 120, 130, 135, 140, 150])

2.

In [41]:
np.where(sales_array > 120)

(array([2, 2, 2, 2]), array([0, 1, 2, 3]))

3.

In [42]:
len(np.where(temps_array > 25)[0])

2

4.

In [49]:
np.sort(temps_array)


array([19.8, 22.5, 25. , 28.1, 30.2])

5.

In [48]:
np.argsort(sales_array.flatten())


array([ 4,  5,  2,  6,  0,  7,  3,  1,  9, 11, 10,  8])

6.

In [47]:
len(np.where(sales_array > 100)[0])


6

7.

In [46]:
temps_array.reshape(5, 1)


array([[22.5],
       [25. ],
       [19.8],
       [30.2],
       [28.1]])

8.


In [45]:
np.sum(sales_array + 10 > 100)


np.int64(9)

9.

In [44]:
np.sqrt(sales_array)


array([[10.        , 10.95445115,  9.48683298, 10.48808848],
       [ 8.94427191,  9.21954446,  9.74679434, 10.        ],
       [12.24744871, 11.40175425, 11.83215957, 11.61895004]])

10.

In [43]:
len(np.where(sales_array == 110)[0])

1

11.

In [54]:
np.square(sales_array)


array([[10000, 14400,  8100, 12100],
       [ 6400,  7225,  9025, 10000],
       [22500, 16900, 19600, 18225]])

12.

In [53]:
threshold = np.percentile(sales_array, 90)
np.sum(sales_array > threshold)


np.int64(2)

13.

In [52]:
np.concatenate((temps_array, np.array([20.0, 21.0])))


array([22.5, 25. , 19.8, 30.2, 28.1, 20. , 21. ])

14.

In [51]:
len(np.where(sales_array >= 130)[0])


4

15.

In [50]:
np.sum(sales_array - 5)


np.int64(1275)