In [1]:
import numpy as np

In [2]:
temps = [23.5, 25.2, 26.8, 24.1, 27.3]
temps_array = np.array(temps)

In [3]:
print(temps_array)

[23.5 25.2 26.8 24.1 27.3]


In [4]:
temps_shape = temps_array.shape
print(temps_shape)

(5,)


In [5]:
temps_ndim = temps_array.ndim 
print(temps_ndim)


1


In [6]:
temps_size = temps_array.size
print(temps_size)

5


In [7]:
temps_dtype = temps_array.dtype
print(temps_dtype)

float64


In [8]:
temps_slice = temps_array[:3] 
print(temps_slice)


[23.5 25.2 26.8]


In [9]:
temps_plus_2 = temps_array + 2
print(temps_plus_2)

[25.5 27.2 28.8 26.1 29.3]


In [10]:
temps_sqrt = np.sqrt(temps_array)
print(temps_sqrt)

[4.84767986 5.01996016 5.17687164 4.90917508 5.22494019]


In [11]:
temps_squared = temps_array ** 2 
print(temps_squared)

[552.25 635.04 718.24 580.81 745.29]


In [12]:
temps_minus_1 = temps_array - 1
print(temps_minus_1)

[22.5 24.2 25.8 23.1 26.3]


In [13]:
temps_sum = np.sum(temps_array)
print(temps_sum)

126.89999999999999


In [14]:
temps_std = np.std(temps_array) 
print(temps_std)


1.4770240350109407


In [15]:
temps_mean = np.mean(temps_array)
print(temps_mean)

25.38


In [16]:
temps_std = np.std(temps_array) 
print(temps_std)

1.4770240350109407


In [17]:
temps_max = np.max(temps_array) 
print(temps_max)

27.3


In [18]:
temps_min = np.min(temps_array) 
print(temps_min)

23.5


In [19]:
temps_median = np.median(temps_array) 
print(temps_median)

25.2


In [20]:
ps_reshaped = temps_array.reshape(5, 1 )
print(ps_reshaped)

[[23.5]
 [25.2]
 [26.8]
 [24.1]
 [27.3]]


In [21]:
temps_unique = np.unique(temps_array)
print(temps_unique)

[23.5 24.1 25.2 26.8 27.3]


In [22]:
temps_unique = np.unique(temps_array)
print(temps_unique)

[23.5 24.1 25.2 26.8 27.3]


In [23]:
temps_where = np.where(temps_array > 25)
print(temps_where)


(array([1, 2, 4]),)
